version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: zimmer_postgres
    environment:
      POSTGRES_DB: zimmer_dashboard
      POSTGRES_USER: zimmer_user
      POSTGRES_PASSWORD: your_secure_password_here
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zimmer_user -d zimmer_dashboard"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis (Optional - for caching)
  redis:
    image: redis:7-alpine
    container_name: zimmer_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Backend API
  backend:
    build: ./zimmer-backend
    container_name: zimmer_backend
    environment:
      - DATABASE_URL=postgresql://zimmer_user:your_secure_password_here@postgres:5432/zimmer_dashboard
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - HOST=0.0.0.0
      - PORT=8000
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./zimmer-backend:/app
      - ./uploads:/app/uploads
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: 