version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://zimmer_user:zimmer_password@db:5432/zimmer_db
      - JWT_SECRET_KEY=your_super_secret_jwt_key_here_make_it_long_and_random
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEVELOPMENT_MODE=true
      - ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    depends_on:
      - db
    volumes:
      - .:/app
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=zimmer_db
      - POSTGRES_USER=zimmer_user
      - POSTGRES_PASSWORD=zimmer_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 