"""two factor authentication

Revision ID: 4f0e39ed0f71
Revises: eb9453897829
Create Date: 2025-09-04 14:51:42.926526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f0e39ed0f71'
down_revision: Union[str, None] = 'eb9453897829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('twofa_enabled', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('twofa_secret', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('twofa_secret')
        batch_op.drop_column('twofa_enabled')

    # ### end Alembic commands ###
