"""automation health fields

Revision ID: 8833e569d472
Revises: cb5137d9fe20
Create Date: 2025-08-28 15:04:38.984006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8833e569d472'
down_revision: Union[str, None] = 'cb5137d9fe20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('health_check_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('health_status', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('last_health_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('health_details', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('is_listed', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_automations_health_status'), ['health_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_automations_is_listed'), ['is_listed'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automations_is_listed'))
        batch_op.drop_index(batch_op.f('ix_automations_health_status'))
        batch_op.drop_column('is_listed')
        batch_op.drop_column('health_details')
        batch_op.drop_column('last_health_at')
        batch_op.drop_column('health_status')
        batch_op.drop_column('health_check_url')

    # ### end Alembic commands ###
